### ISSUE TITLE
The process tries to extract "secrets.PRIVATE_KEY" from the description

### ISSUE THREAD

**Issue by artembondadefiyeld** [joshjohanning/approveops#2]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/100587071/177383998-1b6aa9b4-2fcc-4d7f-a3d2-a638c631f3ec.png">

**Comment by joshjohanning** [comment]
Ahh, who knew! Good catch @artembondadefiyeld. Thanks for creating the issue, I just fixed with v1.0.3 and re-tagged v1. 🎉
